addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 7a8fc248-698a-43ae-8691-100d355437e9
after_success:
- ./df-build.sh
branches: ''
cache:
  directories:
  - $HOME/.m2
  - $HOME/android-sdk-linux
  - $HOME/.m2
git:
  depth: 10
install: mvn -T 2 -Ptravis -DskipTests=true -B -V install
language: java
matrix:
  include:
  - before_install:
    - if [ ! -d $HOME/android-sdk-linux ]; then curl -s https://storage.googleapis.com/zxing-build/android-sdk-linux.tar.bz2
      | bunzip2 | tar xf - -C $HOME; fi
    - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
      $HOME/.m2/settings.xml
    - ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.6.201602180812/jacoco-0.7.6.201602180812.zip '
    - ' unzip -o jacoco-0.7.6.201602180812.zip  '
    - ' cd lib  '
    - ' mv * ../  '
    - ' cd ..  '
    - ' chmod a+x *  '
    - ' curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install
      | bash  '
    - ' cd $PWD  '
    - ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec  '
    - ' travis_wait 60 mvn test -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true
      -Drat.skip=true -Drat.ignoreErrors=true test-compile -Dgpg.skip=true  '
    - ' cd ${PWD}  '
    - ' echo '' ----- Debug info for jacoco and env data -----''  '
    - ' echo ''Current dir is: $PWD'' '
    - ' echo ''Jacoco cov: ''  '
    - ' find . -name ''*.exec''  '
    - ' echo '' ----------------------------------------------1111'' '
    env: ANDROID_HOME=$HOME/android-sdk-linux
    jdk: oraclejdk8
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=7a8fc248-698a-43ae-8691-100d355437e9
script:
- mvn -T 2 -Ptravis ${JACOCO} test
- find $HOME/.m2/repository/com/google/zxing -path "*SNAPSHOT/*" -delete
- find $HOME/.m2/repository/com/google/zxing -name "*SNAPSHOT" -type d -delete
sudo: false
# Modified by Insights Service at 2016-10-10 22:49:25.168435
